export default function Footer(){ return (
<footer className="bg-[#0A0A0A] text-white rounded-t-[40px] pt-16 pb-8">
  <div className="max-w-[1280px] mx-auto px-6">
    <div className="grid md:grid-cols-12 gap-10">
      <div className="md:col-span-5"><div className="flex items-center gap-2.5"><div className="w-9 h-9 bg-white text-black grid place-items-center rounded-xl font-black">G</div><div><div className="font-black text-[16px] leading-none">GospeLove <span className="text-[#EC4899]">♥</span></div><div className="text-[9px] tracking-[0.2em] text-white/40 font-bold mt-1">LOVE SHARED. LIVES TRANSFORMED.</div></div></div><p className="text-[13px] text-white/60 mt-5 max-w-[300px] leading-relaxed">A joyful Jesus family in Adur, Kerala - worshipping, serving villages, raising disciples. You belong here.</p><div className="flex gap-2.5 mt-6"><div className="w-9 h-9 bg-white/10 hover:bg-white/20 rounded-full grid place-items-center text-[12px] cursor-pointer transition">IG</div><div className="w-9 h-9 bg-white/10 hover:bg-white/20 rounded-full grid place-items-center text-[12px] cursor-pointer transition">YT</div><div className="w-9 h-9 bg-white/10 hover:bg-white/20 rounded-full grid place-items-center text-[12px] cursor-pointer transition">FB</div></div></div>
      <div className="md:col-span-2"><div className="text-[11px] font-black tracking-[0.15em] text-white/30">EXPLORE</div><div className="mt-4 space-y-3 text-[14px] text-white/70"><div className="hover:text-white cursor-pointer">Home</div><div className="hover:text-white cursor-pointer">About</div><div className="hover:text-white cursor-pointer">Ministries</div><div className="hover:text-white cursor-pointer">Sermons</div><div className="hover:text-white cursor-pointer">Events</div></div></div>
      <div className="md:col-span-2"><div className="text-[11px] font-black tracking-[0.15em] text-white/30">VISIT</div><div className="mt-4 space-y-2 text-[13px] text-white/60 leading-relaxed"><div>GospeLove Church, Adur</div><div>Pathanamthitta, Kerala 691552</div><div className="flex items-center gap-2 mt-3 text-white/80"><span>🕒</span> Sundays 10 AM IST</div></div></div>
      <div className="md:col-span-3"><div className="bg-white/[0.06] border border-white/10 rounded-[20px] p-6 backdrop-blur"><div className="font-bold text-[14px]">New here? Start here 💛</div><div className="text-[12px] text-white/60 mt-2 leading-relaxed">Get service times, location, and a personal welcome message on WhatsApp.</div><button className="w-full mt-5 bg-white text-black rounded-full py-2.5 text-[13px] font-bold hover:bg-white/90 transition">Get Welcome Pack</button></div></div>
    </div>
    <div className="mt-14 border-t border-white/10 pt-7 flex flex-wrap justify-between gap-4 text-[11px] text-white/40"><div>© 2026 GospeLove Ministry - Adur, Kerala - Made with love & prayer.</div><div className="flex gap-4 items-center"><span className="hover:text-white/60 cursor-pointer">Privacy</span><span>-</span><span className="hover:text-white/60 cursor-pointer">Terms</span><span className="bg-white/[0.06] border border-white/10 rounded-full px-3 py-1.5 flex items-center gap-2"><span className="w-1.5 h-1.5 bg-emerald-400 rounded-full animate-pulse"/>GospeLove Ministry - Preview Version</span></div></div>
  </div>
</footer>
) }
